name: CI

on:
  push:
    branches:
      - master
    paths:
      - "version.json"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm
        git push -u origin upm
      env:
        PKG_ROOT: ArtInFart
